# Generated by Django 4.2.4 on 2023-09-01 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('born_date', models.DateField(null=True)),
                ('register_date', models.DateField(auto_now=True)),
                ('resubscription_date', models.DateField(null=True)),
                ('unsubscribe_date', models.DateField(null=True)),
                ('dni', models.BigIntegerField(null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('comments', models.TextField(null=True)),
                ('condition', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('plan_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField()),
                ('day', models.IntegerField()),
                ('exercise', models.ManyToManyField(to='exercises.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('repetitions', models.IntegerField()),
                ('unity', models.CharField(max_length=20)),
                ('weight', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.exercise')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.routine')),
            ],
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('routines', models.ManyToManyField(to='exercises.routine')),
            ],
        ),
        migrations.CreateModel(
            name='PersonPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField()),
                ('Planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.planning')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.plan'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_date', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.person')),
            ],
        ),
        migrations.CreateModel(
            name='MuscularGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.TextField(null=True)),
                ('exercises', models.ManyToManyField(to='exercises.exercise')),
            ],
        ),
    ]
