# Generated by Django 4.2.4 on 2023-09-01 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='routineexercise',
            name='name',
        ),
    ]
