# Generated by Django 4.2.4 on 2023-09-04 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_remove_routine_exercise_remove_routineexercise_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musculargroup',
            name='exercises',
        ),
        migrations.CreateModel(
            name='MuscularGroupExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('muscular_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.musculargroup')),
            ],
        ),
    ]
