# Generated by Django 4.2.4 on 2023-09-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_remove_musculargroup_exercises_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musculargroup',
            name='exercises',
            field=models.ManyToManyField(to='exercises.exercise'),
        ),
        migrations.DeleteModel(
            name='MuscularGroupExercises',
        ),
    ]
