# Generated by Django 4.2.4 on 2023-09-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_musculargroup_exercises_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
