# Generated by Django 4.2.4 on 2023-09-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_person_last_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_activity']},
        ),
        migrations.AddField(
            model_name='payment',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='dni',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
