# Generated by Django 4.2.4 on 2023-09-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_alter_person_options_payment_bonus_alter_person_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='new_payment_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='condition',
            field=models.IntegerField(default=1),
        ),
    ]
