# Generated by Django 4.2.4 on 2023-09-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_person_new_payment_date_alter_person_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='payment_advice_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
